@startuml
hide circle
skinparam classAttributeIconSize 0
title Klasse

class Standort{
    - name: String
    - location: Double
    --
    + getName(): String
    + setName(name: String)
    + getLocation(): Double
    + setLocation(location: Double)

    }

class Icon{
    - name: String
    - iconList: mutableListOf[]
    --
    + getName(): String
    + setName(name: String)
    + addSonne(icon:[Sonne])
    + addRegen(icon:[Regen])
    + addWolken(icon:[Wolken])
    + addSchnee(icon:[Schnee])
    + addWind(icon:[Wind])
    + addNebel(icon:[Nebel])
    + getIconList(): iconList[]

    }

class Schnee{
    - art: String
    - intensität: String
    - schneeFallHoeheMM: Double
    - schneeInsgesamtInMM: Double
    - schneeHoeheLetzterTagMM: Double
    --
    + setArt(art:String)
    + getArt(): String
    + setIntensität(intensität:String)
    + getIntensität(): String
    + setSchneefallHoeheMM(schneeFallHoeheMM:Double)
    + setSchneeHoeheLetzterTagInMM(setSchneeHoeheLetzterTagInMM: Double)
    - berechneSchneeHoehe((schneeFallHoeheMM:Double,schneeHoeheLetzterTagMM):schneeInsgesamtInMM

class Wind{
    - art = String
    - geschwindigkeit = Int
    - maxGeschwindigkeit = Int
    - einheit = String
    - richtung= String
    --
    + setArt(art:String)
    + getArt(): String
    + setWindgeschwindigkeit(geschwindigkeit: Int)
    + getWindgeschwindigkeit():Int
    + setWindRichtung(richtung: String)
    + getWindRichtung(): String
    + setEinheit(Einheit: String)
    }



    }

@enduml