@startuml
hide circle
skinparam classAttributeIconSize 0
title Objekte


object __karte__{
    - name = ""
    - farbe = ""
    - grösse = Int
    __
    + build()
    + addStandorte()
    + addSymbole()
    + addTempAnzeige()

    }

object __createIcon__{
    name = "actualWeatherIcon"
    actualStatus : listOf = Icon.iconList
    __
    createIcon()
    deleteIcon()
    }



@enduml
